# Generated by Django 3.2.7 on 2021-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(default='<django.db.models.fields.CharField>', unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='film_genre', to='movies.Genre', verbose_name='genre'),
        ),
    ]
